version: '3.7'

volumes:
  volume_pp3:

services:
  # -------------------------------------------------------------
  # DATABASE - MYSQL server engine
  # -------------------------------------------------------------

  mysql_service_main:
    container_name: 'mysql_container_main'
    image: 'mysql:latest'
    volumes:
      # - './DATABASE/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './DATABASE/init-instituto.sql:/docker-entrypoint-initdb.d/init-instituto.sql'
      - './DATABASE/init-grafana.sql:/docker-entrypoint-initdb.d/init-grafana.sql'
      - 'volume_pp3:/var/lib/mysql'
    hostname: 'localhost'
    env_file:
      - './.env'
      - './DATABASE/.env'
    ports:
      - ${OS_DB_PORT}:${DOCKER_DB_PORT}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # -------------------------------------------------------------
  # ADMINER - database adminer
  # -------------------------------------------------------------

  adminer_service_main:
    container_name: 'adminer_container_main'
    depends_on:
      mysql_service_main:
        condition: service_healthy
    image: 'adminer:latest'
    hostname: 'localhost'
    env_file:
      - './.env'
      - './DATABASE/.env'
    ports:
      - ${OS_ADMINER_PORT}:${DOCKER_ADMINER_PORT}
    restart: 'unless-stopped'

  # -------------------------------------------------------------
  # API - EXPRESS JS
  # -------------------------------------------------------------

  api_service_main:
    container_name: 'api_container_main'
    depends_on:
      mysql_service_main:
        condition: service_healthy
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './API:/var/www/html'
    command: 'bash -c "yarn config set network-timeout 600000 -g && yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    env_file:
      - './.env'
      - './API/.env'
    ports:
      - ${OS_API_PORT}:${DOCKER_API_PORT}
    tty: true
    restart: 'always'

  # -------------------------------------------------------------
  # UI - REACT JS
  # -------------------------------------------------------------

  ui_service_main:
    container_name: 'ui_container_main'
    depends_on:
      - 'api_service_main'
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './UI:/var/www/html'
    command: 'bash -c "yarn config set network-timeout 600000 -g && yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    env_file:
      - './.env'
      - './UI/.env'
    ports:
      - ${OS_UI_PORT}:${DOCKER_UI_PORT}
    tty: true
    stdin_open: true
    restart: 'always'

  # -------------------------------------------------------------
  # REPORTING - GRAFANA
  # -------------------------------------------------------------
 
  grafana:
    container_name: 'grafana_container_main'
    depends_on:
      mysql_service_main:
        condition: service_healthy
    image: 'grafana/grafana:latest' #:7.5.4
    volumes:
      - './REPORTING/grafana-data:/var/lib/grafana'
      - './REPORTING/img/chester-institute-icon.png:/usr/share/grafana/public/img/fav32.png'
      - './REPORTING/img/chester-institute-icon.svg:/usr/share/grafana/public/img/grafana_icon.svg'
    env_file:
      - './.env'
      - './REPORTING/.env'
    ports:
      - ${OS_GF_PORT}:${DOCKER_GF_PORT}
    user: '1000' # Cambiar por el resultado de: "id -u"
    restart: 'always'


# -------------------------------------------------------------