version: '3'
services:

  # DATABASE - MYSQL server engine
  DATABASE:
    image: 'mysql:5.7.35'
    command: '--init-file /docker-entrypoint-initdb.d/init.sql'
    volumes:
      - './DATABASE/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './DATABASE/my-datavolume:/var/lib/mysql'
    hostname: 'localhost'
    env_file:
      - './.env'
      - 'DATABASE/.env'
    ports:
      - ${OS_DB_PORT}:${DOCKER_DB_PORT}
    restart: 'always'

  # ADMINER - database adminer
  ADMINER:
    depends_on:
      - 'DATABASE'
    image: 'adminer:latest'
    hostname: 'localhost'
    ports:
      - ${OS_ADMINER_PORT}:${DOCKER_ADMINER_PORT}
    env_file:
      - 'ADMINER/.env'
    restart: 'unless-stopped'

  # API - EXPRESS JS
  API:
    depends_on:
      - 'DATABASE'
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './API:/var/www/html'
    command: 'bash -c "yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - ${OS_API_PORT}:${DOCKER_API_PORT}
    env_file:
      - './.env'
      - 'API/.env'
    tty: true
    restart: 'always'

  # UI - REACT JS
  UI:
    depends_on:
      - 'API'
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './UI:/var/www/html'
    command: 'bash -c "yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - ${OS_UI_PORT}:${DOCKER_UI_PORT}
    env_file:
      - './.env'
      - 'UI/.env'
    tty: true
    stdin_open: true
    restart: 'always'
