version: '3'
services:

  # DB_SERVER - MYSQL server engine
  DB_SERVER:
    image: 'mysql:5.7.35'
    command: '--init-file /docker-entrypoint-initdb.d/init.sql'
    volumes:
      - './DB_SERVER/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './DB_SERVER/my-datavolume:/var/lib/mysql'
    hostname: 'localhost'
    env_file:
      - './.env'
      - './DB_SERVER/.env'
    ports:
      - ${OS_DB_PORT}:${DOCKER_DB_PORT}
    restart: 'always'

  # DB_ADMINER - database adminer
  DB_ADMINER:
    depends_on:
      - 'DB_SERVER'
    image: 'adminer:latest'
    hostname: 'localhost'
    ports:
      - ${OS_ADMINER_PORT}:${DOCKER_ADMINER_PORT}
    env_file:
      - './DB_ADMINER/.env'
    restart: 'unless-stopped'

  # API_REST - EXPRESS JS
  API_REST:
    depends_on:
      - 'DB_SERVER'
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './API_REST:/var/www/html'
    command: 'bash -c "yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - ${OS_API_PORT}:${DOCKER_API_PORT}
    env_file:
      - './.env'
      - './API_REST/.env'
    tty: true
    restart: 'always'

  # UI_WEB - REACT JS
  UI_WEB:
    depends_on:
      - 'API_REST'
    image: 'node:14'
    working_dir: '/var/www/html'
    volumes:
      - './UI_WEB:/var/www/html'
    command: 'bash -c "yarn && yarn dev"'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    hostname: 'localhost'
    ports:
      - ${OS_UI_PORT}:${DOCKER_UI_PORT}
    env_file:
      - './.env'
      - './UI_WEB/.env'
    tty: true
    stdin_open: true
    restart: 'always'
