version: '3.7'
services:

  mysql_service:
    container_name: mysql_container
    image: mysql:latest
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "${OS_DB_PORT}:${DOCKER_DB_PORT}"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  adminer_service:
    container_name: adminer_container
    depends_on:
      - mysql_service
    image: adminer:latest
    env_file:
      - .env
    ports:
      - "${OS_ADMINER_PORT}:${DOCKER_ADMINER_PORT}"

volumes:
  mysql_data: